version: '3.9'

networks:
    db_new:
        driver: bridge

volumes:
  pgdata_dellinwt:

services:
  telegram_bot:
    build: .
    environment:
      HOST: postgresql
      DB: ${DB}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      PORT: ${PORT}
      R_DB: ${R_DB}
      U_AUTO: ${U_AUTO}
      U_CONTACTS: ${U_CONTACTS}
      U_CITY: ${U_CITY}
      U_BASES: ${U_BASES}
      TOKEN: ${TOKEN}
    volumes:
      - ./logs:/src/logs
    networks:
      - db_new
    depends_on:
      - postgresql
    entrypoint: bash -c  "python main.py"
  app_server:
    build: .
    environment:
      HOST: postgresql
      DB: ${DB}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      PORT: ${PORT}
      R_DB: ${R_DB}
      U_AUTO: ${U_AUTO}
      U_CONTACTS: ${U_CONTACTS}
      U_CITY: ${U_CITY}
      U_BASES: ${U_BASES}
      TOKEN: ${TOKEN}
    ports:
      - "5000:5000"
    networks:
      - db_new
    depends_on:
      - postgresql
    entrypoint: bash -c  "gunicorn --bind 0.0.0.0:5000 --chdir app_server wsgi:app"
  postgresql:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB}
      POSTGRES_HOST: localhost
    volumes:
      - pgdata_dellinwt:/var/lib/postgresql/data
    networks:
      - db_new
