"""first migration

Revision ID: 681a4ea21d62
Revises: 
Create Date: 2023-10-25 18:31:31.263845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681a4ea21d62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
