"""start_fuel

Revision ID: 88715de4cf92
Revises: f66fe51d235b
Create Date: 2023-11-11 20:19:52.294567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88715de4cf92'
down_revision = 'f66fe51d235b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel', sa.Column('s_fuel', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fuel', 's_fuel')
    # ### end Alembic commands ###
