"""new model Tokens

Revision ID: edfb36e4282a
Revises: 681a4ea21d62
Create Date: 2023-10-25 18:58:02.085069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edfb36e4282a'
down_revision = '681a4ea21d62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
