"""fuel notes, contacts id

Revision ID: f66fe51d235b
Revises: 2a19428471a1
Create Date: 2023-11-11 19:55:01.465721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f66fe51d235b'
down_revision = '2a19428471a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel', sa.Column('s_odo', sa.Integer(), nullable=True))
    op.add_column('fuel', sa.Column('f_odo', sa.Integer(), nullable=True))
    op.add_column('fuel', sa.Column('f_fuel', sa.Float(), nullable=True))
    op.add_column('fuel', sa.Column('econ_fuel', sa.Float(), nullable=True))
    op.add_column('fuel', sa.Column('over_fuel', sa.Float(), nullable=True))
    op.add_column('fuel', sa.Column('auto', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fuel', 'auto', ['auto'], ['id'])
    op.add_column('user', sa.Column('snils', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'snils')
    op.drop_constraint(None, 'fuel', type_='foreignkey')
    op.drop_column('fuel', 'auto')
    op.drop_column('fuel', 'over_fuel')
    op.drop_column('fuel', 'econ_fuel')
    op.drop_column('fuel', 'f_fuel')
    op.drop_column('fuel', 'f_odo')
    op.drop_column('fuel', 's_odo')
    # ### end Alembic commands ###
