from handlers.calc_fuel.s_odometer import register_handlers_cf_s_odo
from handlers.calc_fuel.f_odometer import register_handlers_cf_f_odo
from handlers.calc_fuel.fuel import register_handlers_cf_fuel
from handlers.calc_fuel.refuel import register_handlers_cf_refuel
from handlers.calc_fuel.sel_auto import register_handlers_cf_sel_auto
from handlers.calc_fuel.confirm import register_handlers_cf_confirm
