from funcs.fuel_calculate import calc_fuel
from funcs import report_time
from funcs.converttime import convert_time
from funcs.total_time import totaltime
from funcs.convert_timedelta import converttimedelta
from funcs.loggingg import log
from funcs.get_workdays import get_wdays
from funcs.generate_profile import gen_profile
from funcs.report_turnover import gen_turnover
from funcs.send_instruction import send_inst
